---
# CSS-CrossAccountVPCPeering
AWSTemplateFormatVersion: 2010-09-09
Description: Create a assumable role for cross account VPC peering
Resources:
  VpcPeerRole:
    Type: 'AWS::IAM::Role'
    DeletionPolicy: Delete
    Properties:
      RoleName: !Sub CSS-CrossAccount-VPCPeering
      AssumeRolePolicyDocument:
        Statement:
          - Principal:
              AWS:
                - !Sub arn:aws:iam::099999999999:root
                - !Sub arn:aws:iam::099999999999:root
                - !Sub 'arn:aws:iam::099999999999:root'
            Action:
              - 'sts:AssumeRole'
            Effect: Allow
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 'ec2:AcceptVpcPeeringConnection'
                Resource: '*'
Outputs:
  RoleARN:
    Value: !GetAtt
      - VpcPeerRole
      - Arn
